server:
  port: 9098
  host: localhost

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

razorpay:
  key: rzp_test_YourKeyHere
  secret: YourSecretHere

  
zipkin:
  baseUrl: http://127.0.0.1:9411/

