server:
  port: 9095
  address: localhost

app:
  # Use forward-slash style and the requested absolute path
  location: "D://gitrepo//neer-seva//backendapp//springboot//ns-image-service//neerseva-images"

spring:
  application:
    name: NS-IMAGE-SERVICE

  # Provide datasource at the root so env.getProperty("spring.datasource.url") is available for diagnostics
  datasource:
    url: jdbc:mysql://localhost:3306/ns-image-db?autoReconnect=true&useSSL=false
    username: root
    password: "ConDyn6!"
    driver-class-name: com.mysql.cj.jdbc.Driver

# Default Eureka settings (can be overridden per-profile)
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
